---
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.3}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60  # How often (in seconds) to scan the DAGs directory for new files.
    
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
    _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    _AIRFLOW_DB_MIGRATE: 'true'
    _AIRFLOW_WWW_USER_CREATE: 'true'

  volumes:
    - airflow-dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"

services:
  postgres:
    image: postgres:13
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student-de
      POSTGRES_DB: student
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow:
    <<: *airflow-common
    command: standalone
    ports:
      - "7004:8080"
    restart: always
    environment:
      <<: *airflow-common-env

  vsc:
    image: cr.yandex/crp1r8pht0n0gl25aug1/vsc-checkers-etl:latest
    environment:
      PLAYGROUND_API: https://d5dg1j9kt695d30blp03.apigw.yandexcloud.net
      AF_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      AF_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      AF_ENDPOINT: http://airflow:8080
      X_API_KEY: 5f55e6c0-e9e5-4a9c-b313-63c01fc31460
      PG_LOGIN: student
      PG_PW: student-de
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: student
      DE_CHECK_V: de-start-sprint-9/r2024-12-23
    ports:
      - 7090:8000
    volumes:
      - lessons:/lessons
      - airflow-dags:/lessons/dags

volumes:
  airflow-dags:
  postgres-db-volume:
  lessons: 
